### ISSUE TITLE
Support HTTP/3 with suffix

### ISSUE THREAD

**Issue by PSSGCSim** [pd4d10/http-indicator#10]
Add support for HTTP/3 with version suffix. For example "h3-27". Example of real world encounter:

![Screenshot_20200802_211329](https://user-images.githubusercontent.com/42121756/89130457-3b9e3c00-d505-11ea-933b-867a6f86c1d8.png)

**Comment by pd4d10** [comment]
Hi, @PSSGCSim , Thanks for your feedback!

It has been fixed and published to Chrome and Mozilla web store. It may take a while for the review to complete
