### ISSUE TITLE
Causes Chrome to use > 100% CPU

### ISSUE THREAD

**Issue by joeshaw** [pd4d10/http-indicator#13]
Since 1.0.0 was released I've noticed Chrome using over 100% CPU.  Going through my extensions one by one I found this one to be the culprit.

It only affects the main Chrome process.  I haven't noticed that a particular tab seems to trigger this.  Looking at the code I don't see anything obviously amiss, and the code hasn't changed much between 0.1.0 and 1.0.0, so I'm not sure how best to debug this on my end.  Suggestions welcome!

**Comment by pd4d10** [comment]
Finally reproduced it in my machine

Probably related to https://bugs.chromium.org/p/chromium/issues/detail?id=1231683

**Comment by pd4d10** [comment]
> Probably related to https://bugs.chromium.org/p/chromium/issues/detail?id=1231683

There seem to be no determined plans to fix this issue, so downgrade it to manifest v2 to fix it temporarily

Submitted it to Chrome Web Store, waiting for review
