### ISSUE TITLE
QUIC test site

### ISSUE THREAD

**Issue by FranklinYu** [pd4d10/http-indicator#4]
Is there any way to verify QUIC? I haven't met any site with QUIC support including Google and YouTube which some sources claim to support QUIC.

**Comment by pd4d10** [comment]
Hi, @FranklinYu , The red icon [here](https://github.com/pd4d10/http-indicator/blob/master/icons/hq.png) indicates that the current website has QUIC enabled.

**Comment by FranklinYu** [comment]
Yes I know that, but I cannot find a website that really enables QUIC. Therefore I have no way to know whether QUIC support is still working.

**Comment by pd4d10** [comment]
Have you tried https://www.google.com?

**Comment by pd4d10** [comment]
For debugging, you can open devtools and run the following code:

```js
performance.getEntriesByType('navigation')[0].nextHopProtocol
```

**Comment by FranklinYu** [comment]
Does Google show QUIC for you? It currently shows HTTP/2 for me. The code above gives `"h2"`. I’m using macOS and `chrome://flags/#enable-quic` has been enabled. I suspect that QUIC isn’t supported on macOS; tomorrow I’ll try on another machine.

**Comment by pd4d10** [comment]
> For debugging, you can open devtools and run the following code:
> 
> ```js
> performance.getEntriesByType('navigation')[0].nextHopProtocol
> ```

In my case it shows `"http/2+quic/46"` at https://www.google.com/, using Chrome at macOS.

**Comment by pd4d10** [comment]
Hi, @FranklinYu , is the problem solved?

I'm not sure, probably google.com has some sort of AB tests for different network environments.

**Comment by FranklinYu** [comment]
The issue was fixed by re-installing Chrome. Thanks!
